### ISSUE TITLE
Error when using exclude

### ISSUE THREAD

**Issue by jamietre** [davglass/license-checker#162]
Hard to reproduce consistently - sometimes it fails, other times it doesn't. For example:

```
> license-checker --exclude 'GPL-2.0'
/Users/jamiet/.nvm/versions/node/v8.9.4/lib/node_modules/license-checker/node_modules/spdx-expression-parse/parse.js:52
    if (t.type === 'DOCUMENTREF') {
          ^

TypeError: Cannot read property 'type' of null
    at parseLicenseRef (/Users/jamiet/.nvm/versions/node/v8.9.4/lib/node_modules/license-checker/node_modules/spdx-expression-parse/parse.js:52:11)
    at parseAtom (/Users/jamiet/.nvm/versions/node/v8.9.4/lib/node_modules/license-checker/node_modules/spdx-expression-parse/parse.js:102:7)
    at parseBinaryOp (/Users/jamiet/.nvm/versions/node/v8.9.4/lib/node_modules/license-checker/node_modules/spdx-expression-parse/parse.js:109:18)
    at parseBinaryOp (/Users/jamiet/.nvm/versions/node/v8.9.4/lib/node_modules/license-checker/node_modules/spdx-expression-parse/parse.js:109:18)
    at module.exports (/Users/jamiet/.nvm/versions/node/v8.9.4/lib/node_modules/license-checker/node_modules/spdx-expression-parse/parse.js:133:14)
    at module.exports (/Users/jamiet/.nvm/versions/node/v8.9.4/lib/node_modules/license-checker/node_modules/spdx-expression-parse/index.js:7:10)
    at module.exports (/Users/jamiet/.nvm/versions/node/v8.9.4/lib/node_modules/license-checker/node_modules/spdx-satisfies/index.js:110:29)
    at /Users/jamiet/.nvm/versions/node/v8.9.4/lib/node_modules/license-checker/lib/index.js:383:40
    at Array.forEach (<anonymous>)
    at /Users/jamiet/.nvm/versions/node/v8.9.4/lib/node_modules/license-checker/lib/index.js:367:30
```

There is a package with this license: `(GPL-2.0 OR MIT)`

- running it with a random single string also fails, e.g. `> license-checker --exclude 'FOO'`
- running it with a random string + MIT works: `> license-checker --exclude 'FOO, MIT'`

Also - generally, I am a bit concerned about the way `exclude` works. For example, when I run it on our repo using the sample exclude from the readme:

`> license-checker --exclude 'MIT, MIT OR X11, BSD, ISC`

I get packages with these licenses: Apache-2.0, WTFPL, Unlicensed, Apache*, and so on, which seems correct. When I add WTFPL:

`> license-checker --exclude 'MIT, MIT OR X11, BSD, ISC, WTFPL`

There is no output at all! Shouldn't it be showing me still the Apache, unlicensed, etc... e.g. everything from the prior run, except WTFPL?

**Comment by DesHorsley** [comment]
I have the same issue, running the example from the read me `license-checker --exclude 'MIT, MIT OR X11, BSD, ISC'` crashes with the error pasted above.

Even if I just run it with 'MIT' as the only parameter.

**Comment by cmur2** [comment]
I encounter the same problem with the latest version 24.0.1 with license-checker:
```
license-checker --production --exclude "MIT;BSD-3-Clause"
/home/foo/bar/node_modules/spdx-expression-parse/parse.js:52
    if (t.type === 'DOCUMENTREF') {
          ^

TypeError: Cannot read property 'type' of null
    at parseLicenseRef (/home/foo/bar/node_modules/spdx-expression-parse/parse.js:52:11)
    at parseAtom (/home/foo/bar/node_modules/spdx-expression-parse/parse.js:102:7)
    at parseBinaryOp (/home/foo/bar/node_modules/spdx-expression-parse/parse.js:109:18)
    at parseBinaryOp (/home/foo/bar/node_modules/spdx-expression-parse/parse.js:109:18)
    at module.exports (/home/foo/bar/node_modules/spdx-expression-parse/parse.js:133:14)
    at module.exports (/home/foo/bar/node_modules/spdx-expression-parse/index.js:7:10)
    at module.exports (/home/foo/bar/node_modules/spdx-satisfies/index.js:110:29)
    at /home/foo/bar/node_modules/license-checker/lib/index.js:389:64
    at Array.forEach (<anonymous>)
    at /home/foo/bar/node_modules/license-checker/lib/index.js:375:30
```

**Comment by davglass** [comment]
I'm not sure this is an issue with `license-checker` itself or if it's the `spdx-satisfies` module. The line that throws the error is:

```js
 } else if (spdxCorrect(license) && spdxSatisfies(spdxCorrect(license), spdxExcluder)) {
```

That to me means that the `spdx-satisfies` isn't doing the right thing.

**Comment by cmur2** [comment]
That could be true, I circumvented for now using `license-checker --production --exclude "MIT OR ISC OR Apache-2.0"` with the spdx syntax and that seems to work for my use case...

**Comment by TorstenDittmann** [comment]
On Windows using `"` instead of `'` is working for me. Use `\"` in `package.json` for correct syntax.
