### ISSUE TITLE
crashes, when options --production and --unknownonly are used together

### ISSUE THREAD

**Issue by BePo65** [davglass/license-checker#275]
Calling license-checker with options crashes, when options `--production --unknownonly` throws:

```
>npx license-checker --onlyunknown --production
Found error
Error: No packages found in this path..
    at D:\Projekte\github\start-server-and-test\node_modules\license-checker\lib\index.js:353:19
    at D:\Projekte\github\start-server-and-test\node_modules\read-installed\read-installed.js:142:5
    at D:\Projekte\github\start-server-and-test\node_modules\read-installed\read-installed.js:263:14
    at cb (D:\Projekte\github\start-server-and-test\node_modules\slide\lib\async-map.js:47:24)
    at D:\Projekte\github\start-server-and-test\node_modules\read-installed\read-installed.js:263:14
    at cb (D:\Projekte\github\start-server-and-test\node_modules\slide\lib\async-map.js:47:24)
    at D:\Projekte\github\start-server-and-test\node_modules\read-installed\read-installed.js:263:14
    at cb (D:\Projekte\github\start-server-and-test\node_modules\slide\lib\async-map.js:47:24)
    at D:\Projekte\github\start-server-and-test\node_modules\read-installed\read-installed.js:263:14
    at asyncMap (D:\Projekte\github\start-server-and-test\node_modules\slide\lib\async-map.js:27:18)
```

**Comment by tiny-ben-tran** [comment]
I have the same issue even when using only `--production` option
